### ISSUE TITLE
Project life tracker

### ISSUE THREAD

**Issue by IanOliv** [IanOliv/Health-Tracker#1]
- [ ] Create a initial structure
- [ ] Setting server  
   - [ ] body parsing
   - [ ] auth middleware
   - [ ] connection to the database

- [ ] User
    - [ ] create user
    - [ ] update user 
    - [ ] read  self user data 
    - [ ] read  specific user  data 
    - [ ] delete user data
    - [ ] update user password

- [ ] User measurement
    - [ ] create measurement
    - [ ] read all user measurement
    - [ ] read  specific user measurement 
    - [ ] update user measurement
    - [ ] delete user measurement

- [ ] User meals w/ calories and weight
    - [ ] create meals
    - [ ] read all user meals
    - [ ] read  specific user meals 
    - [ ] update user meals
    - [ ] delete user meals

- [ ] User activities w/ calories, time  and bpm(AVG)
    - [ ] create activities
    - [ ] read all user activities
    - [ ] read  specific user activities 
    - [ ] update user activities
    - [ ] delete user activities

**Comment by pgsilva** [comment]
boa garoto
